version: '3.7'

services:

  client:
    image: nginx:alpine
    container_name: devops-test
    restart: always
    volumes:
      - type: bind
        source: ./index.html
        target: /usr/share/nginx/html/index.html
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 3001:80